import { createMetaBrowser } from 'vitalvida-meta-tracking/browser';

const pixelId = typeof __META_PIXEL_ID__ !== 'undefined' ? __META_PIXEL_ID__ : '';

const CAPI_ENDPOINT = '/api/meta-capi';

export const meta = createMetaBrowser({
  pixelId,
  capiEndpoint: CAPI_ENDPOINT,
  country: 'ng',
  onError: (err) => {
    console.error('[Meta Browser]', err);
  },
});

declare global {
  interface Window {
    __vvPageViewEventId?: string;
  }
}

/**
 * Sends ONLY the server-side (CAPI) PageView, reusing the event ID generated by
 * the inline Meta Pixel bootstrap in index.html <head> (window.__vvPageViewEventId).
 *
 * The browser PageView is fired from <head> before React loads, so calling
 * meta.firePageView() here would emit a SECOND browser PageView with a different
 * event ID and break deduplication. Instead, this posts the CAPI event with the
 * same event ID so Meta dedupes the browser + server pair into one PageView.
 *
 * Falls back to the full package flow (browser + CAPI, internally deduped) if
 * the head bootstrap did not run for some reason.
 */
export async function firePageViewCapi(): Promise<void> {
  if (typeof window === 'undefined') return;

  const eventId = window.__vvPageViewEventId;
  if (!eventId) {
    await meta.firePageView();
    return;
  }

  const { externalId, fbp, fbc } = meta.getTrackingContext();

  let sourceUrl = window.location.href;
  try {
    const url = new URL(sourceUrl);
    url.searchParams.delete('fbclid');
    url.hash = '';
    sourceUrl = url.toString();
  } catch {
    // keep raw href
  }

  await fetch(CAPI_ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      event_name: 'PageView',
      event_id: eventId,
      event_time: Math.floor(Date.now() / 1000),
      action_source: 'website',
      event_source_url: sourceUrl,
      user_data: {
        external_id: externalId,
        ...(fbc ? { fbc } : {}),
        ...(fbp ? { fbp } : {}),
        country: 'ng',
      },
    }),
  });
}
